
(function(){
"use strict";
const d=document, header=d.querySelector(".site-header"), navToggle=d.querySelector(".nav-toggle"), navMenu=d.querySelector(".nav-menu"), navLinks=d.querySelectorAll(".nav-link"), topBtn=d.querySelector(".back-to-top"), progress=d.querySelector(".reading-progress");
function headerState(){ if(header) header.classList.toggle("is-scrolled", window.scrollY>12); }
function closeMenu(){ if(!navToggle||!navMenu)return; navToggle.classList.remove("is-open"); navMenu.classList.remove("is-open"); navToggle.setAttribute("aria-expanded","false"); }
function setupNav(){ if(!navToggle||!navMenu)return; navToggle.setAttribute("aria-expanded","false"); navToggle.addEventListener("click",()=>{const open=navToggle.classList.toggle("is-open"); navMenu.classList.toggle("is-open",open); navToggle.setAttribute("aria-expanded",String(open));}); navLinks.forEach(a=>a.addEventListener("click",closeMenu)); window.addEventListener("resize",()=>{if(innerWidth>860)closeMenu();}); d.addEventListener("keydown",e=>{if(e.key==="Escape")closeMenu();});}
function activeNav(){ const file=location.pathname.split("/").pop()||"index.html"; navLinks.forEach(a=>{const href=a.getAttribute("href")||""; const f=href.split("/").pop(); if(f===file||(file.startsWith("article-")&&f==="insights.html")){a.classList.add("active");a.setAttribute("aria-current","page");}});}
function reveal(){ const items=d.querySelectorAll(".reveal"); if(!("IntersectionObserver"in window)){items.forEach(i=>i.classList.add("is-visible"));return;} const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");io.unobserve(e.target);}})},{threshold:.14,rootMargin:"0px 0px -40px 0px"}); items.forEach((i,idx)=>{i.style.transitionDelay=Math.min(idx*40,220)+"ms";io.observe(i);});}
function faq(){ d.querySelectorAll(".faq-item").forEach((item,idx)=>{const q=item.querySelector(".faq-question"), ans=item.querySelector(".faq-answer"); if(!q||!ans)return; ans.id=ans.id||"faq-answer-"+(idx+1); q.setAttribute("aria-expanded","false"); q.setAttribute("aria-controls",ans.id); q.addEventListener("click",()=>{const open=item.classList.contains("is-open"); d.querySelectorAll(".faq-item").forEach(o=>{o.classList.remove("is-open"); const oq=o.querySelector(".faq-question"), oa=o.querySelector(".faq-answer"); if(oq)oq.setAttribute("aria-expanded","false"); if(oa)oa.style.maxHeight=null;}); if(!open){item.classList.add("is-open");q.setAttribute("aria-expanded","true");ans.style.maxHeight=ans.scrollHeight+"px";}});});}
function progressBar(){ if(!progress)return; const h=d.documentElement.scrollHeight-innerHeight; progress.style.width=(h>0?Math.min(scrollY/h*100,100):0)+"%"; }
function topVisible(){ if(topBtn) topBtn.classList.toggle("is-visible",scrollY>520); }
function counters(){ const counters=d.querySelectorAll(".count-up"); const run=el=>{const target=Number(el.dataset.count||0), dur=Number(el.dataset.duration||1400), start=performance.now(); function tick(t){const p=Math.min((t-start)/dur,1), e=1-Math.pow(1-p,3); el.textContent=Math.round(target*e).toLocaleString(); if(p<1)requestAnimationFrame(tick); else el.textContent=target.toLocaleString();} requestAnimationFrame(tick);}; if(!("IntersectionObserver"in window)){counters.forEach(run);return;} const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){run(e.target);io.unobserve(e.target);}})},{threshold:.45}); counters.forEach(c=>io.observe(c));}
function toc(){ const list=d.querySelector(".toc ol"), article=d.querySelector(".article-content"); if(!list||!article)return; const hs=article.querySelectorAll("h2"); list.innerHTML=""; hs.forEach((h,i)=>{h.id=h.id||"section-"+(i+1); const li=d.createElement("li"), a=d.createElement("a"); a.href="#"+h.id; a.textContent=h.textContent; li.appendChild(a); list.appendChild(li);});}
function contactForm(){ const form=d.querySelector("[data-contact-form]"); if(!form)return; form.addEventListener("submit",e=>{e.preventDefault(); const name=form.querySelector('[name="name"]').value.trim(), email=form.querySelector('[name="email"]').value.trim(), subject=form.querySelector('[name="subject"]').value.trim()||"Message for Ely Ganthier", message=form.querySelector('[name="message"]').value.trim(); const body=["Name: "+name,"Email: "+email,"","Message:",message].join("\n"); location.href="mailto:support@gsobllc.com?subject="+encodeURIComponent(subject)+"&body="+encodeURIComponent(body);});}
function copyEmail(){ d.querySelectorAll("[data-copy-email]").forEach(b=>{const original=b.textContent; b.addEventListener("click",async()=>{const em=b.getAttribute("data-copy-email"); try{await navigator.clipboard.writeText(em);b.textContent="Email copied";setTimeout(()=>b.textContent=original,1400);}catch(e){location.href="mailto:"+em;}});});}
function external(){ d.querySelectorAll('a[href^="http"]').forEach(a=>{try{const u=new URL(a.href); if(u.hostname!==location.hostname){a.target="_blank";a.rel="noopener noreferrer";}}catch(e){}});}
function lazyImages(){ const imgs=d.querySelectorAll("img"); imgs.forEach(img=>{if(!img.loading)img.loading="lazy"; if(!img.decoding)img.decoding="async";}); const first=d.querySelector(".hero img,.page-hero img,.article-cover img"); if(first){first.loading="eager"; first.setAttribute("fetchpriority","high");}}
let ticking=false; function onScroll(){ if(ticking)return; requestAnimationFrame(()=>{headerState();progressBar();topVisible();ticking=false;}); ticking=true;}
function init(){setupNav();activeNav();reveal();faq();counters();toc();contactForm();copyEmail();external();lazyImages();headerState();progressBar();topVisible(); if(topBtn)topBtn.addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"})); addEventListener("scroll",onScroll,{passive:true});}
if(d.readyState==="loading")d.addEventListener("DOMContentLoaded",init); else init();
})();
